name: modal_progress_indicator
description: A modal progress indicator that blocks access to widgets while it's visible.
version: 1.0.0
homepage: https://github.com/phimary/modal_progress_indicator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
